services:
  fastapi:
    build: 
      context: .
      dockerfile: src/backend/Dockerfile
    container_name: planner-api
    ports:
      - "8000:8000"
    env_file:
      - .env
  nicegui:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    container_name: nicegui
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - HOST_NAME=planner-api
    depends_on:
      - fastapi
