services:
  fastapi:
    build: 
      context: .
      dockerfile: src/backend/Dockerfile
    container_name: planner-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./secrets/serviceAccountKey.json:/app/secrets/serviceAccountKey.json:ro
    
  vue:
    build:
      context: src/frontend
      dockerfile: Dockerfile
    container_name: vue
    ports:
      - "8080:80"
    depends_on:
      - fastapi
