[project]
name = "ns-shift-planner-frontend"
version = "0.1.0"
description = "Shift planner frontend service"
requires-python = ">=3.13"
dependencies = [
    "cachetools>=5.5.2",
    "fastapi[standard]>=0.115.12",
    "python-dotenv>=1.1.0",
    "nicegui>=2.19.0",
]

dev = [
    "pytest>=8.4.0",
]
